---
- osx_defaults:
    host: currentHost
    domain: /Library/Preferences/com.apple.loginwindow
    key: GuestEnabled
    type: boolean    
    value: false
    state: present

- command: networksetup -setdnsservers Wi-Fi 1.0.0.1 1.1.1.1
